Update dbBuild.yml

diff --git a/.github/workflows/dbBuild.yml b/.github/workflows/dbBuild.yml
--- a/.github/workflows/dbBuild.yml
+++ b/.github/workflows/dbBuild.yml
@@ -94,11 +94,14 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
       - name: Verify download
-        run: |
-          if (Test-Path "D:\testload\Python_2DB.exe") {
-            Write-Output "File successfully downloaded"
-          } else {
-            Write-Error "File download failed"
-            exit 1
-          }
+        run: | 
+            cd D:\testload
+            |
+            dir
+          # if (Test-Path "D:\testload\Python_2DB.exe") {
+          #   Write-Output "File successfully downloaded"
+          # } else {
+          #   Write-Error "File download failed"
+          #   exit 1
+          # }
           
